version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./db.env # app/db.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    mem_limit: 768m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: dydwoj/soltech-final-backend:latest
    container_name: soltech-final-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - ./db.env
      - ./google.env
      - ./jwt.env
    environment:
      SPRING_PROFILES_ACTIVE: prod,oauth
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    restart: always

  frontend:
    image: dydwoj/soltech-final-frontend:latest
    container_name: soltech-final-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: always

volumes:
  mysql_data:
