name: Build and Push Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend Maven Build
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 권한 부여
      - name: Grant execute permission for mvnw
        working-directory: soltech/project
        run: chmod +x mvnw

      # aud-7 설치
      - name: Install aud7-embedded jar
        working-directory: soltech/project
        shell: bash
        run: |
          echo "[DEBUG] pwd = $(pwd)"
          ls -al libs || true
          test -f libs/aud7-embedded.jar || (echo "❌ libs/aud7-embedded.jar not found"; exit 1)

          ./mvnw install:install-file \
            -Dfile=libs/aud7-embedded.jar \
            -DgroupId=com.matrix \
            -DartifactId=aud7-embedded \
            -Dversion=1.0.0 \
            -Dpackaging=jar
      
      # Querydsl Q 클래스 생성
      - name: Generate Q classes & Build (A-plan)
        working-directory: soltech/project
        shell: bash
        run: |
          set -e
          echo "[DEBUG] mvn clean package (skip tests)"
          ./mvnw -U -B -DskipTests clean package

          echo "[DEBUG] list generated sources"
          ls -R target/generated-sources/annotations || true

      # Build & Push Backend
      - name: Build & Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/soltech-final-backend:latest \
            -f soltech/project/Dockerfile soltech/project
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/soltech-final-backend:latest

      # Build frontend
      - name: Build frontend
        working-directory: soltechreact
        run: |
          yarn install --frozen-lockfile
          yarn build

      # Build & Push Frontend
      - name: Build & Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/soltech-final-frontend:latest \
            -f soltechreact/Dockerfile soltechreact
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/soltech-final-frontend:latest

      # EC2 접속 후 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존 백엔드/프론트만 정리
            docker stop soltech-backend || true
            docker stop soltech-frontend || true
            docker rm soltech-backend || true
            docker rm soltech-frontend || true

            # 기존 이미지 정리 (백엔드/프론트만)
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/soltech-backend:latest || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/soltech-frontend:latest || true

            # 최신 이미지 pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/soltech-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/soltech-frontend:latest

            # env 파일 생성 (mysql 건드리지 않고, backend 실행할 때만 사용)
            echo "${{ secrets.DOCKER_ENV_DB }}" > /home/ubuntu/db.env
            echo "${{ secrets.DOCKER_ENV_GOOGLE }}" > /home/ubuntu/google.env
            echo "${{ secrets.DOCKER_ENV_JWT }}" > /home/ubuntu/jwt.env

            # 백엔드 실행
            docker run -d --name soltech-backend \
              --env-file /home/ubuntu/db.env \
              --env-file /home/ubuntu/google.env \
              --env-file /home/ubuntu/jwt.env \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/soltech-backend:latest \
              --spring.profiles.active=prod

            # 프론트 실행
            docker run -d --name soltech-frontend \
              -p 5173:5173 \
              ${{ secrets.DOCKERHUB_USERNAME }}/soltech-frontend:latest

